# File: .streamlit/config.toml

[server]
headless = true

[theme]
base="dark"
primaryColor="#9700FD"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font = "sans serif"
